version: '3.8'

services:
    app:
        env_file:
            - .env
        image: kytel0925/php:8.3-debian-apache-dev
        container_name: user-manager
        ports:
            - '8087:80'
        volumes:
            - '.:/app'
        environment:
            HTTP_PORT: '80'
        restart: always
